package:
  format-version: "1.0.0"
  name: "bootloader_apps_ota"
  version: "v3.0.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "dev"
    - name: "wireless_services"
      type: "package"
      version: "dev"

